from collections.abc import Sequence
from os import PathLike
from pathlib import Path
from typing import ClassVar, TypeAlias

PathInput: TypeAlias = str | PathLike[str]
Inputs: TypeAlias = PathInput | Sequence[PathInput]
__version__: str

class Insta360Error(Exception): ...
class Insta360IOError(Insta360Error): ...
class InvalidMediaError(Insta360Error): ...
class UnsupportedCameraError(Insta360Error): ...
class MissingCalibrationError(Insta360Error): ...
class AmbiguousOpticalSetupError(Insta360Error): ...
class MissingCapabilityError(Insta360Error): ...
class GpuUnavailableError(MissingCapabilityError): ...
class CancelledError(Insta360Error): ...
class MediaProcessingError(Insta360Error): ...
class GpuProcessingError(MediaProcessingError): ...
class ConflictingOpticsError(Insta360Error): ...

class Housing:
    AUTO: ClassVar[Housing]
    NONE: ClassVar[Housing]
    VENTURE_CASE: ClassVar[Housing]
    DIVE_CASE: ClassVar[Housing]
    SPHERICAL_DIVE_CASE: ClassVar[Housing]
    INVISIBLE_DIVE_CASE: ClassVar[Housing]
    DIVE_CASE_PRO: ClassVar[Housing]

class Environment:
    AUTO: ClassVar[Environment]
    AIR: ClassVar[Environment]
    UNDERWATER: ClassVar[Environment]

class LensAccessory:
    AUTO: ClassVar[LensAccessory]
    NONE: ClassVar[LensAccessory]
    CLIP_ON_LENS_GUARD: ClassVar[LensAccessory]
    ADHESIVE_SPHERE_LENS_GUARD: ClassVar[LensAccessory]
    PROTECTOR_A: ClassVar[LensAccessory]
    PROTECTOR_S: ClassVar[LensAccessory]
    PROTECTOR_AS: ClassVar[LensAccessory]
    ND16: ClassVar[LensAccessory]
    ND32: ClassVar[LensAccessory]
    ND64: ClassVar[LensAccessory]
    ND128: ClassVar[LensAccessory]

class MountingAccessory:
    AUTO: ClassVar[MountingAccessory]
    NONE: ClassVar[MountingAccessory]
    DIVE_BUDDY: ClassVar[MountingAccessory]

class UnderwaterColorMode:
    OFF: ClassVar[UnderwaterColorMode]
    LEGACY: ClassVar[UnderwaterColorMode]
    AI: ClassVar[UnderwaterColorMode]

class UnderwaterColorOptions:
    @property
    def mode(self) -> UnderwaterColorMode: ...
    @property
    def strength(self) -> float | None: ...
    @property
    def balance(self) -> float | None: ...
    @property
    def style(self) -> int | None: ...
    def __init__(
        self,
        *,
        mode: UnderwaterColorMode | None = ...,
        strength: float | None = ...,
        balance: float | None = ...,
        style: int | None = ...,
    ) -> None: ...

class Stabilization:
    OFF: ClassVar[Stabilization]
    FLOW_STATE: ClassVar[Stabilization]
    DIRECTION_LOCK: ClassVar[Stabilization]

class RollingShutterCorrection:
    AUTO: ClassVar[RollingShutterCorrection]
    OFF: ClassVar[RollingShutterCorrection]
    REQUIRED: ClassVar[RollingShutterCorrection]

class ProcessingBackend:
    AUTO: ClassVar[ProcessingBackend]
    CPU: ClassVar[ProcessingBackend]
    GPU: ClassVar[ProcessingBackend]

class ColorConversion:
    AUTO: ClassVar[ColorConversion]
    PRESERVE: ClassVar[ColorConversion]
    I_LOG_TO_REC709: ClassVar[ColorConversion]

class EffectiveBackend:
    CPU: ClassVar[EffectiveBackend]
    GPU: ClassVar[EffectiveBackend]
    UNKNOWN: ClassVar[EffectiveBackend]

class ImageFormat:
    PNG: ClassVar[ImageFormat]
    JPEG: ClassVar[ImageFormat]

class AudioPolicy:
    COPY: ClassVar[AudioPolicy]
    DROP: ClassVar[AudioPolicy]

class MediaAcceleration:
    AUTO: ClassVar[MediaAcceleration]
    SOFTWARE: ClassVar[MediaAcceleration]
    HARDWARE: ClassVar[MediaAcceleration]

class ExportPhase:
    PROBING: ClassVar[ExportPhase]
    DECODING: ClassVar[ExportPhase]
    STITCHING: ClassVar[ExportPhase]
    ENCODING: ClassVar[ExportPhase]
    FINALIZING: ClassVar[ExportPhase]
    UNKNOWN: ClassVar[ExportPhase]

class StitchConfig:
    housing: Housing
    environment: Environment
    lens_accessory: LensAccessory
    mounting_accessory: MountingAccessory
    underwater_color: UnderwaterColorOptions
    stabilization: Stabilization
    rolling_shutter: RollingShutterCorrection
    backend: ProcessingBackend
    color_conversion: ColorConversion
    width: int | None
    height: int | None

    def __init__(
        self,
        *,
        housing: Housing | None = ...,
        environment: Environment | None = ...,
        lens_accessory: LensAccessory | None = ...,
        mounting_accessory: MountingAccessory | None = ...,
        underwater_color: UnderwaterColorOptions | None = ...,
        stabilization: Stabilization | None = ...,
        rolling_shutter: RollingShutterCorrection | None = ...,
        backend: ProcessingBackend | None = ...,
        color_conversion: ColorConversion | None = ...,
        width: int | None = ...,
        height: int | None = ...,
    ) -> None: ...
    @staticmethod
    def underwater_photogrammetry(
        *,
        housing: Housing | None = ...,
        mounting_accessory: MountingAccessory | None = ...,
        underwater_color: UnderwaterColorOptions | None = ...,
        rolling_shutter: RollingShutterCorrection | None = ...,
        backend: ProcessingBackend | None = ...,
        color_conversion: ColorConversion | None = ...,
        width: int | None = ...,
        height: int | None = ...,
    ) -> StitchConfig: ...

class OpticalSelection:
    @property
    def housing(self) -> Housing: ...
    @property
    def environment(self) -> Environment: ...
    @property
    def lens_accessory(self) -> LensAccessory: ...
    @property
    def mounting_accessory(self) -> MountingAccessory: ...

class OpticalInspection:
    @property
    def detected(self) -> OpticalSelection | None: ...
    @property
    def evidence(self) -> str | None: ...
    @property
    def encoded_lens_id(self) -> int | None: ...
    @property
    def ambiguity(self) -> str | None: ...

class OpticalResolution:
    @property
    def requested(self) -> OpticalSelection: ...
    @property
    def detected(self) -> OpticalSelection: ...
    @property
    def effective(self) -> OpticalSelection: ...
    @property
    def evidence(self) -> str: ...
    @property
    def source_lens_id(self) -> int: ...
    @property
    def target_lens_id(self) -> int: ...
    @property
    def sensor_crop_applied(self) -> bool: ...

class VideoTrackInfo:
    @property
    def index(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def codec(self) -> str: ...

class TrailerInfo:
    @property
    def offset(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def version(self) -> int: ...
    @property
    def record_count(self) -> int: ...

class MediaInfo:
    @property
    def optics(self) -> OpticalInspection: ...
    @property
    def inputs(self) -> list[Path]: ...
    @property
    def camera(self) -> str: ...
    @property
    def camera_name(self) -> str | None: ...
    @property
    def serial(self) -> str | None: ...
    @property
    def firmware(self) -> str | None: ...
    @property
    def duration_seconds(self) -> float | None: ...
    @property
    def fps(self) -> float | None: ...
    @property
    def video_tracks(self) -> list[VideoTrackInfo]: ...
    @property
    def offset_versions(self) -> list[int]: ...
    @property
    def optical_profiles(self) -> list[str]: ...
    @property
    def gyro_sample_count(self) -> int: ...
    @property
    def exposure_sample_count(self) -> int: ...
    @property
    def trailer(self) -> TrailerInfo: ...

class GpuAdapterInfo:
    @property
    def name(self) -> str: ...
    @property
    def backend(self) -> str: ...
    @property
    def device_type(self) -> str: ...
    @property
    def vendor(self) -> int: ...
    @property
    def device(self) -> int: ...
    @property
    def driver(self) -> str: ...
    @property
    def driver_info(self) -> str: ...

class GpuFailure:
    @property
    def code(self) -> str: ...
    @property
    def stage(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def adapter(self) -> GpuAdapterInfo | None: ...

class BackendReport:
    @property
    def requested(self) -> ProcessingBackend: ...
    @property
    def selected(self) -> EffectiveBackend: ...
    @property
    def adapter(self) -> GpuAdapterInfo | None: ...
    @property
    def fallback(self) -> GpuFailure | None: ...

class ExportResult:
    @property
    def optics(self) -> OpticalResolution | None: ...
    @property
    def outputs(self) -> list[Path]: ...
    @property
    def frames_written(self) -> int: ...
    @property
    def elapsed_seconds(self) -> float: ...
    @property
    def backend(self) -> BackendReport: ...

class ExportProgress:
    @property
    def phase(self) -> ExportPhase: ...
    @property
    def completed(self) -> int: ...
    @property
    def total(self) -> int | None: ...
    @property
    def media_time_seconds(self) -> float | None: ...
    @property
    def elapsed_seconds(self) -> float: ...
    @property
    def estimated_remaining_seconds(self) -> float | None: ...

class ExtractionReport:
    @property
    def output_dir(self) -> Path: ...
    @property
    def manifest_path(self) -> Path: ...
    @property
    def input_count(self) -> int: ...
    @property
    def stream_count(self) -> int: ...
    @property
    def record_count(self) -> int: ...
    @property
    def files(self) -> list[Path]: ...
    @property
    def warnings(self) -> list[str]: ...

class StreamInfo:
    @property
    def input_index(self) -> int: ...
    @property
    def stream_index(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def codec(self) -> str: ...
    @property
    def codec_id(self) -> int: ...
    @property
    def time_base(self) -> tuple[int, int]: ...
    @property
    def start_time(self) -> int | None: ...
    @property
    def duration(self) -> int | None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def codec_extradata(self) -> bytes: ...

class MediaSource:
    @property
    def streams(self) -> list[MediaStream]: ...
    @property
    def video_streams(self) -> list[MediaStream]: ...

class MediaStream:
    @property
    def info(self) -> StreamInfo: ...
    @property
    def source_path(self) -> Path: ...
    def open_packets(self) -> PacketReader: ...
    def open_video(self) -> VideoFrameReader: ...

class StreamSideData:
    @property
    def kind(self) -> int: ...
    @property
    def data(self) -> bytes: ...

class EncodedPacket:
    @property
    def input_index(self) -> int: ...
    @property
    def stream_index(self) -> int: ...
    @property
    def data(self) -> bytes: ...
    @property
    def pts(self) -> int | None: ...
    @property
    def dts(self) -> int | None: ...
    @property
    def duration(self) -> int: ...
    @property
    def time_base(self) -> tuple[int, int]: ...
    @property
    def flags(self) -> int: ...
    @property
    def key_frame(self) -> bool: ...
    @property
    def corrupt(self) -> bool: ...
    @property
    def source_position(self) -> int | None: ...
    @property
    def side_data(self) -> list[StreamSideData]: ...

class DecodedVideoFrame:
    @property
    def data(self) -> bytes: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def timestamp_seconds(self) -> float | None: ...
    @property
    def pts(self) -> int | None: ...
    @property
    def time_base(self) -> tuple[int, int]: ...

class PacketReader:
    @property
    def info(self) -> StreamInfo: ...
    def read_packet(self) -> EncodedPacket | None: ...
    def seek(self, seconds: float) -> None: ...

class VideoFrameReader:
    @property
    def info(self) -> StreamInfo: ...
    def read_frame(self) -> DecodedVideoFrame | None: ...
    def seek(self, seconds: float) -> None: ...
    def frame_at(self, seconds: float) -> DecodedVideoFrame | None: ...

class Capabilities:
    @property
    def underwater_ai_compiled(self) -> bool: ...
    @property
    def image_export(self) -> bool: ...
    @property
    def video_export(self) -> bool: ...
    @property
    def gpu_compiled(self) -> bool: ...
    @property
    def gpu_available(self) -> bool: ...
    @property
    def gpu_adapters(self) -> list[GpuAdapterInfo]: ...
    @property
    def gpu_unavailable_reason(self) -> str | None: ...
    @property
    def hevc_encoders(self) -> list[str]: ...

class ExportJob:
    def cancel(self) -> None: ...
    def is_finished(self) -> bool: ...
    def progress(self) -> ExportProgress | None: ...
    def backend(self) -> BackendReport | None: ...
    def stabilization(self) -> str | None: ...
    def take_warnings(self) -> list[str]: ...
    def wait(self) -> ExportResult: ...

def probe(input: Inputs) -> MediaInfo: ...
def extract(input: Inputs, output_dir: PathInput) -> ExtractionReport: ...
def open_media(input: Inputs) -> MediaSource: ...
def capabilities() -> Capabilities: ...
def export_video(
    input: Inputs,
    output: PathInput,
    *,
    config: StitchConfig | None = ...,
    quality: int = ...,
    audio: AudioPolicy = ...,
    start: float | None = ...,
    duration: float | None = ...,
    acceleration: MediaAcceleration = ...,
) -> ExportResult: ...
def start_export_video(
    input: Inputs,
    output: PathInput,
    *,
    config: StitchConfig | None = ...,
    quality: int = ...,
    audio: AudioPolicy = ...,
    start: float | None = ...,
    duration: float | None = ...,
    acceleration: MediaAcceleration = ...,
) -> ExportJob: ...
def export_frames(
    input: Inputs,
    output_dir: PathInput,
    *,
    indices: Sequence[int] | None = ...,
    timestamps: Sequence[float] | None = ...,
    start: float | None = ...,
    end: float | None = ...,
    fps: float | None = ...,
    config: StitchConfig | None = ...,
    format: ImageFormat = ...,
    quality: int = ...,
    scale_width: int | None = ...,
) -> ExportResult: ...
def start_export_frames(
    input: Inputs,
    output_dir: PathInput,
    *,
    indices: Sequence[int] | None = ...,
    timestamps: Sequence[float] | None = ...,
    start: float | None = ...,
    end: float | None = ...,
    fps: float | None = ...,
    config: StitchConfig | None = ...,
    format: ImageFormat = ...,
    quality: int = ...,
    scale_width: int | None = ...,
) -> ExportJob: ...
